export const memories = [
  {
    id: 1,
    title: "School Exams",
    description: "I still remember those school exams when we were sitting together. I was trying my best to copy answers, and instead of helping, you kept threatening to call the invigilator. I don't think you ever realized how funny that was. Looking back now, it's one of my favourite memories of us. 😂",
    date: "2018",
    x: 20,
    y: 25,
    connectTo: [2],
  },
  {
    id: 2,
    title: "Cricket",
    description: "Endless evenings playing cricket with friends.",
    date: "2019",
    x: 40,
    y: 40,
    connectTo: [1, 3],
  },
  {
    id: 3,
    title: "MS Dhoni",
    description: "The player who inspired confidence and calmness.",
    date: "2020",
    x: 65,
    y: 20,
    connectTo: [2, 4],
  },
  {
    id: 4,
    title: "Birthday",
    description: "A birthday full of unforgettable surprises.",
    date: "2023",
    x: 80,
    y: 35,
    connectTo: [3, 5],
  },
  {
    id: 5,
    title: "Hidden Star",
    description: "A memory waiting to be discovered.",
    date: "Unknown",
    x: 55,
    y: 70,
    connectTo: [4],
  },
];